Move proxy as optional permission/availabe in the options page
mozilla/multi-account-containers pull request #2140
Opened 2021-09-29 19:58 UTC by maxxcrawford

This PR does the following: 
- Moves proxy to optional permission in the manifest
- Adds a checkbox in the options page to toggle this permission/feature
- Show/hide the proxy settings in the container mgmt panel based on the permission status

2021-09-29 19:58 UTC, maxxcrawford commented
cc/ @kendallcorner

2021-09-30 02:00 UTC, groovecoder requested changes

2021-09-30 02:00 UTC, groovecoder commented on src/js/background/messageHandler.js
> +        response = assignManager.init();
Is this the right UX?

1. Enable proxy support
2. Assign Container1 to use proxy1
3. Open sensitiveSite1 in Container1 (thru proxy1)
4. Disable proxy support
5. Reload tab from step 3
   * sensitiveSite1 is reloaded without a proxy without any other warning

2021-09-30 18:58 UTC, maxxcrawford commented on src/js/popup.js
> +      document.querySelector(".proxy-container-settings").classList.remove("is-hidden");
Yes – This is just a framework for @lesleyjanenorton to key off of.

2021-09-30 19:20 UTC, closed without merging

2021-09-30 19:20 UTC, maxxcrawford commented
Closing this for now.