Remember choice for default containers in the "Always open in" confirm page
mozilla/multi-account-containers pull request #2649
Opened 2024-07-18 15:59 UTC by rafeerahman

**Before submitting your pull request**

- [x] I agree to license my code under the [MPL 2.0 license](https://www.mozilla.org/en-US/MPL/2.0/).
- [x] I rebased my work on top of the main branch.
- [x] I ran `npm test` and all tests passed.
- [x] I added test coverages if relevant.

# Description

When a user is on the confirm-page after re-opening a site they chose to 'always open in a container', if they click "Remember my choice" and then "Open in current tab" (default container), this is not remembered. i.e. The next time they open the site, they are prompted to this screen again. 

![image](https://github.com/user-attachments/assets/95187f20-3666-439a-bebb-c832be1104c5)

## Type of change

*Select all that apply.*

- [x] Bug fix
- [ ] New feature
- [ ] Major change (fix or feature that would cause existing functionality to work differently than in the current version)

Tag issues related to this pull request:

* https://github.com/mozilla/multi-account-containers/issues/2603

2024-07-18 18:18 UTC, rafeerahman commented
Also looking into integrating / fixing https://github.com/mozilla/multi-account-containers/pull/2617, which tries to remember the choice when switching to a container that is not the "default container" (i.e. not "Open in current tab").

2024-07-19 19:12 UTC, groovecoder requested changes
Couple blocking changes.

Can you write out the steps you used to spot-check this? I tried:

1. Go to accounts.firefox.com
2. In the browserAction menu, choose "Always Open This Site in..."
3. In the list of containers, choose "Work"
4. Close the tab
5. Open a new window
6. Go to accounts.firefox.com

Expected Result:
* I should be prompted to confirm I want to open the site in a Work tab

Actual Result:
* I'm not prompted to confirm I want to open the site in a Work tab

2024-07-19 19:15 UTC, groovecoder commented
Also, please change the commit message to start with `fix #2603:` so that GitHub will automatically link this PR with the corresponding issue.

2024-07-23 15:41 UTC, rafeerahman commented on src/js/background/assignManager.js
> +      title: browser.i18n.getMessage("openBookmarkInContainerTab"),
looks like I amended to most recent merge commit by accident

2024-07-30 14:28 UTC, groovecoder requested changes
Thanks @rafeerahman I was able to reproduce the bug and the fix on youtube.com.

There's still one more bug that I think is worth fixing:

1. Go to youtube.com
2. In the browserAction menu, choose "Always Open This Site in..."
3. Choose the work container
4. Open youtube.com in a new tab.
5. On the confirmation page prompt, check "Remember my decision for this site" then click "Open in current tab"
6. Open youtube.com in a new tab
   * [ ] verify that there is no confirmation page.
   * [ ] verify youtube.com opens in default/non-container tab
8. Open the work containers "site list"
   * [ ] verify that it is empty.
9. Open a new work tab
10. Go to youtube.com

Expected results:
youtube.com automatically opens in default/non-container tab without prompting

Actual results:
youtube.com opens in work container tab

2024-08-23 16:36 UTC, achernyakevich-sc commented on src/js/confirm-page.js
> +  }
Maybe optimize it by something like:

```
if (neverAsk) {
  await browser.runtime.sendMessage({
    method: "neverAsk",
    neverAsk: true,
    cookieStoreId: currentCookieStoreId,
    pageUrl: redirectUrl,
    defaultContainer: !currentContainer
  });
}
```

2024-08-23 16:44 UTC, rafeerahman commented on src/js/confirm-page.js
> +  }
Thanks!

2024-08-27 18:47 UTC, groovecoder approved these changes

2024-08-27 18:47 UTC, merged